<?php

# This file was automatically generated by the MediaWiki 1.18.1 installer. If you make manual changes, please keep track in 
# case you need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings and their default values, but don't forget to make changes 
# in _this_ file, not there.
#
# Further documentation for configuration settings may be found at: 
# http://www.mediawiki.org/wiki/Manual:Configuration_settings Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
    exit;
}

$wgUsePathInfo = false;

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;
$wgSitename = "FA Forever Wiki";
$wgMetaNamespace = "FA_Forever_Wiki";
## The URL base path to the directory containing the wiki; defaults for all runtime URL paths are based off of this. For 
## more information on customizing the URLs please see: http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgScriptExtension = ".php";
## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://wiki.faforever.com";
## The relative URL path to the skins directory
$wgStylePath = "$wgScriptPath/skins";
## UPO means: this is also a user preference option
$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO
$wgEmergencyContact = "support@faforever.com"; 
$wgPasswordSender = "support@faforever.com";
#$wgEnotifUserTalk = false; # UPO $wgEnotifWatchlist = false; # UPO $wgEmailAuthentication = true;
## Database settings
$wgDBtype = "mysql"; 
$wgDBserver = "172.17.0.4"; 
$wgDBname = "faf_wiki"; 
$wgDBuser = "faf_wiki"; 
$wgDBpassword = "";
# MySQL specific settings
$wgDBprefix = "";
# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";
# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;
## Shared memory settings
$wgMainCacheType = CACHE_NONE; 
$wgMemCachedServers = array();
## To enable image uploads, make sure the 'images' directory is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true; $wgImageMagickConvertCommand = "/usr/bin/convert";
# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons = false;
## If you use ImageMagick (or any other shell command) on a Linux server, this will need to be set to the name of an 
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";
## If you want to use image uploads under safe mode, create the directories images/archive, images/thumb and images/temp, 
## and make them all writable. Then uncomment this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;
## Set $wgCacheDirectory to a writable directory on the web server to make your wiki go slightly faster. The directory 
## should not be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";
# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en"; 
$wgSecretKey = "c8f6b8d71484b02d24b740ba2d306c9081344a2bd4546c1462c0b5c9c57eb8d0";
# Site upgrade key. Must be set to a string (default provided) to turn on the web installer while LocalSettings.php is in 
# place
$wgUpgradeKey = "a9453044b4331832";
## Default skin: you can change the default skin. Use the internal symbolic names, ie 'standard', 'nostalgia', 
## 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";
## For attaching licensing metadata to pages, and displaying an appropriate copyright notice / icon. GNU Free Documentation 
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright $wgRightsUrl = ""; 
$wgRightsText = ""; 
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";
# Query string length limit for ResourceLoader. You should only set this if your web server has a query string length limit 
# (then set it to that limit), or if you have suhosin.get.max_value_length set in php.ini (then set it to that value)
$wgResourceLoaderMaxQueryLength = -1;
# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['edit'] = false;
$wgShowIPinHeader = false;
# Enabled Extensions. Most extensions are enabled by including the base extension file here but check specific extension 
# documentation for more details The following extensions were automatically enabled:

$wgEnableEmail = true;
$wgEmailConfirmToEdit = true;
$wgEmailAuthentication = true;

$wgSMTP = array(
 'host' => 'smtp.mandrillapp.com',
 'IDHost' => 'faforever.com',
 'localhost' => 'www.faforever.com',
 'port' => 587,
 'auth' => true,
 'plain' => true,
 'username' => '',
 'password' => ''
);


#require_once( "$IP/extensions/ConfirmEdit/ConfirmEdit.php" );
#require_once( "$IP/extensions/ConfirmEdit/QuestyCaptcha.php");


# End of automatically generated settings. Add more configuration options below.

$wgLogo = "$wgScriptPath/images/icon.png";
$wgCaptchaClass = 'QuestyCaptcha';
$wgCaptchaQuestions[] = array( 'question' => "Type Alliance without the first and last letter in the box to the right.", 'answer' => "llianc" );

require_once "$IP/skins/Vector/Vector.php";
require_once "$IP/skins/dvector/Darkvector.php";

require_once("$IP/extensions/Nuke/Nuke.php");

# require_once("$IP/extensions/ConfirmAccount/ConfirmAccount.php");

#require_once "$IP/extensions/ParserFunctions/ParserFunctions.php";
$wgPFEnableStringFunctions = true;
